Instuctions: Type your code or solution in this notebook. Upload the '.ipynb' file onto Blackboard before Mar. 4 (23:59).

Name: Check Ho Kan

# Problem 1

 Implement the conjugate-gradient method on the following problem
 
 $$\min_{x,y,z}   x^2 + y^2 + 2z^2 - xy + yz -5x - 2y + 7z - 3$$

 (a) Rewrite the function as a quadratic form: 
$$ f(x,y,z)= \frac{1}{2}\left[\begin{array}{ccc} x &y &z \end{array}\right] Q \left[\begin{array}{c} x \\ y \\z  \end{array}\right]- {\bf b}^T \left[\begin{array}{c} x \\x \\z \end{array}\right] + c$$
Print the matrix $Q$, the vector ${\bf b}$ and the constant $c$.

In [147]:
# Answer:
import numpy as np
Q=np.array([[2,-1,0],[-1,2,-1],[0,-1,4]])
b=np.array([[5],[2],[-7]])
c=-3
print(Q);
print(b);
print(c);

[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  4]]
[[ 5]
 [ 2]
 [-7]]
-3


(b) Implement the conjugate-gradient method.

In [176]:
#Answer

theta=np.array([[0],[0],[0]])
d=b-Q@theta
D=d
g=-d
G=g
for i in range(1,3):
    alpha=-(g.T@d)/(d.T@Q@d)
    theta=theta+alpha*d
    g=Q@theta-b
    beta=(g.T@Q@d)/(d.T@Q@d)
    d=-g+beta*d
    D=np.hstack((D,d))
     
alpha=-(g.T@d)/(d.T@Q@d)
theta=theta+alpha*d
g=Q@theta-b
    

(c) Print the result obtained in (b).

In [177]:
#Answer
print(theta)

[[ 3.6]
 [ 2.2]
 [-1.2]]


(d) Show that the conjugate directions are $Q$-orthogonal (where $Q$ is the matrix in the quadratic form).

In [159]:
print(D[:,1]@Q@D[:,0])
print(D[:,2]@Q@D[:,1])
print(D[:,2]@Q@D[:,0])



-1.7763568394002505e-15
-1.101002476922417e-15
2.842170943040401e-14


In [4]:
#Answer
