In [1]:
import matplotlib.pyplot as plt

In [2]:
import numpy as np

In [3]:
X=np.array([[ 1.,  118., 3],
       [ 1.,  257., 3],
       [ 1., 77., 2],
       [ 1., 196., 4],
       [ 1., 168., 3],
        [1., 542., 4.]])

In [4]:
y=np.array([ [221.] ,  [538.] , [180.] , [604], [510], [1225] ])

## Steepest Descent Algorithm

In [5]:
xm=X.mean(axis=0)

In [6]:
xst=X.std(axis=0)

In [7]:
sx = np.array([X[:,0],(X[:,1]-xm[1])/xst[1],(X[:,2]-xm[2])/xst[2]])

In [8]:
X1=sx.T

In [9]:
Q=2*(X1.T)@X1

In [10]:
b=2*(X1.T)@y

Initial guess

In [11]:
th=np.array([[0],[0],[0]])

In [12]:
th_array = th

In [13]:
g=Q@th-b

In [14]:
ng = np.sqrt(np.sum(g**2))

In [15]:
f = (th.T@Q@th)/2 - (b.T)@th

In [16]:
f_array = f

% te = tolerance

In [17]:
te = 0.000001

In [18]:
count=np.array([0])

In [19]:
while ng > te:
    th = th-((g.T)@g)/((g.T)@Q@g)*g
    g = Q@th-b
    ng = np.sqrt(np.sum(g**2))
    f = (th.T@Q@th)/2 - (b.T)@th
    th_array = np.hstack((th_array, th))
    f_array = np.hstack((f_array, f))
    count=count+1

In [20]:
th

array([[546.33333333],
       [284.57913162],
       [ 70.28967753]])

In [21]:
g

array([[-9.09494702e-13],
       [-1.09157554e-08],
       [ 7.92127594e-07]])

In [22]:
ng

7.9220280135977e-07

In [23]:
count

array([57])